### ISSUE TITLE
Scan don't work well

### ISSUE THREAD

**Issue by brunocalado** [marcstraube/foundryvtt-scenery#11]
**Describe the bug**
You can't scan without remove the filename.

**To Reproduce**
1. I select the first file.
2. Click scan
3. It will not show the other files

I can make it work by
1. I remove the file name leaving only the path
2. I click scan 
3. It show all files.
4. But, it start to generate an error about wrong default file
![image](https://user-images.githubusercontent.com/4999783/226174633-f70749b0-3e84-4e5e-8373-780a64208312.png)

**Expected behavior**
I want to insert the Default file and scan.

**Screenshots**
![image](https://user-images.githubusercontent.com/4999783/226174549-1ac4ea9e-26da-4a41-9fbd-1775fe8ffc53.png)

**System information (please complete the following information):**
 - Scenery Version: 112
 - FoundryVTT Version: 10291
 - Browser: chrome
 - FoundryVTT Game System and Version: swade last

**Comment by marcstraube** [comment]
Based on the list of file names you posted, your default file needs to be named `GL_NightmareDragonLair.jpg`, so that the scan will find the variants.

I will close this issue, because I can see no bug here. If I understood something wrong, don't hesitate to re-open the issue.
