### ISSUE TITLE
Compatibility on v11?

### ISSUE THREAD

**Issue by Fridan99** [marcstraube/foundryvtt-scenery#13]
Does it work in v11? Any plan to upgrade to v11?

**Comment by bryancasler** [comment]
This module had been such a huge quality of life improvement for my Curse of Strahd, 5e game, thank you so much for the work you've done on it. I'd love to repay the favor and help sponsor its upgrade to v11. I'd also be happy to post a bounty to the League of Extraordinary Developers and see if they have any takers, if that's preferred.

**Comment by marcstraube** [comment]
Update is now available via FoundryVTT Module Manager

**Comment by bryancasler** [comment]
Thank you @marcstraube, much appreciated
