### ISSUE TITLE
[QUESTION] Update for v12 ?

### ISSUE THREAD

**Issue by p4535992** [marcstraube/foundryvtt-scenery#19]
I wanted to know if this module was abandoned and if there was itnention to update it for v12.

**Comment by Fridan99** [comment]
I join the question.... I think it is a very useful module to migrate to v12.

**Comment by monnierant** [comment]
I have test it with Foundry VTT 12 and it work so i have create a PR to update it.

For those who don't want to wait from it to be avaliable here i have also create a release on my fork.

[Fork scenery for Foundry VTT 12](https://github.com/monnierant/foundryvtt-scenery/releases/download/v1.3.0/module.json)

**Comment by marcstraube** [comment]
Its not abandoned! I just didn't have the time to work on it. I will release an update in the next couple of days.

**Comment by Fridan99** [comment]
Nice 👏🏻

**Comment by marcstraube** [comment]
Scenery 1.2.0 with support for FoundryVTT v12 just released.
