### ISSUE TITLE
Delete button doesn't do anything

### ISSUE THREAD

**Issue by Fashtas** [marcstraube/foundryvtt-scenery#7]
Maybe my misunderstanding of how the system works, but I added a second scene to test, changed views back and forward a few times, then tried to delete the second map.

However, nothing happens when you push delete, no errors, no effect, does not seem possible to delete a scene variation when added

I was not SHOWING the variation when testing, I had selected the original scene for GM and Player. No players were connected to the game at the time

**Comment by marcstraube** [comment]
Hi @Fashtas ,
I can't reproduce the behavior you described. Do you get any errors in your browsers Developer Console?
Do you have other modules enabled? If so, try disabling them; [Find the culprit](https://github.com/Moerill/fvtt-find-the-culprit) may help with that.

**Comment by Fashtas** [comment]
There are no errors appearing on console when I press the delete button. No messages at all appear when I press the button.

I used Find the Culprit to remove all addons except Scenery and the delete button still doesn't work

Using on Chrome Browser, Forge hosted, Foundry V10 Stable, Patch 6 [Build 291]
Using Scenery Addon updated via Forge version 1.1.1
![image](https://user-images.githubusercontent.com/65834768/213326354-a21bdb6a-d5d7-4c99-aede-3ac259767796.png)

**Comment by Fashtas** [comment]
I just tested a fresh install of Foundry (v10 Build 291) installed locally on my PC using *JUST* PF2E module and one single addon, Scenery - Background Image Variation Manager v 1.1.1 installed via Founrdy. 
The delete button does not do anything, no console errors reported. 

I tested delete both on manually added maps using the Folder browse button and maps discovered via "Scan for Variations"

I removed the Foundry version of the addon and used the manifest to install instead (https://github.com/marcstraube/foundryvtt-scenery/releases/latest/download/module.json)
The delete button still doesn't do anything

Most other functions work, however I just noticed the PREVIEW button throws a console error when clicked and otherwise does nothing:
![image](https://user-images.githubusercontent.com/65834768/213599831-23d03382-f6f6-419a-b928-a48703b0b8e6.png)

**Comment by marcstraube** [comment]
I was able to reproduce the behavior within the PF2E system and I'm going to investigate it further.
